# Generated by Django 2.0.2 on 2018-02-05 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='name',
            new_name='nom',
        ),
    ]
