# Generated by Django 2.0.2 on 2018-02-06 20:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='datePublication',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='education',
            name='dateDebut',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='dateFin',
            field=models.DateField(null=True),
        ),
    ]
