# Generated by Django 2.0.2 on 2018-02-06 21:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180206_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='DescriptionFormation',
            new_name='descriptionFormation',
        ),
        migrations.RemoveField(
            model_name='education',
            name='Lieu',
        ),
        migrations.AddField(
            model_name='education',
            name='lieu',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='dateFin',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
