# Generated by Django 2.0.2 on 2018-02-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180206_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='genre',
            field=models.CharField(default='Mobile development', max_length=50),
        ),
    ]
