# Generated by Django 2.0.2 on 2018-02-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_project_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='education',
            name='descriptionFormation',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='education',
            name='lieu',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
