# Generated by Django 2.0.2 on 2018-02-07 11:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180207_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=70)),
                ('dateDebut', models.DateField()),
                ('dateFin', models.DateField(default=django.utils.timezone.now, null=True)),
                ('lieu', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
    ]
