# Generated by Django 2.0.2 on 2018-02-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='descriptonWork',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
