# Generated by Django 2.0.2 on 2018-02-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_work_descriptonwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.TextField(blank=True),
        ),
    ]
