# Generated by Django 2.0.2 on 2018-02-07 12:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_article_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='dateCreation',
            field=models.DateField(blank=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='datePublication',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='published time'),
        ),
        migrations.AlterField(
            model_name='project',
            name='encadrant',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='githubLink',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='video',
            field=models.TextField(blank=True),
        ),
    ]
