# Generated by Django 2.0.2 on 2018-02-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20180207_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='dateCreation',
            field=models.DateField(blank=True, null=True, verbose_name='Creation date'),
        ),
    ]
