# Generated by Django 2.0.2 on 2018-02-11 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20180207_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='dateCreation',
        ),
        migrations.RemoveField(
            model_name='project',
            name='datePublication',
        ),
        migrations.RemoveField(
            model_name='project',
            name='encadrant',
        ),
    ]
